[package]
name = "pngquant-interactive"
version = "0.0.0"
license = "GPL-3.0"
edition = "2021"

[dependencies]
anyhow = "^1.0"
clap = { version = "^4.1", features = ["derive"] }
fltk = "^1.3"
fltk-theme = "^0.6"
imagequant = "^4.0"
png = "^0.17"
rgb = "0.8"
